//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExtra
    {
        public int id { get; set; }
        public string title { get; set; }
        public string salary { get; set; }
        public string department { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
